version: '3.4'
services: 
    db:
        image: mariadb:latest
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - ./local/db:/var/lib/mysql:z
        environment:
            MYSQL_ROOT_PASSWORD: openvpn-access
            MYSQL_DATABASE: openvpn_access
            MYSQL_USER: openvpn-access
            MYSQL_PASSWORD: openvpn-access
    dashboard:
        build:
            context: ./dashboard
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./config:/config:z
            - ./static:/static:z
    backend:
        build: 
            context: ./backend
            dockerfile: ./docker/Dockerfile
        ports:
            - 8080:8080
        environment: 
            MYSQL_PASSWORD: openvpn-access
            DATABASE_URL: mysql://openvpn-access:openvpn-access@db:3306/openvpn_access?schema=public
        logging: 
            driver: json-file
    openvpn:
        build: ./openvpn-docker
        ports:
            - 1194:1194/udp
        volumes:
            - ./local/pki:/etc/openvpn/pki:z
        cap_add:
            - NET_ADMIN
        environment:
            REQ_COUNTRY: US
            REQ_PROVINCE: California
            REQ_CITY: San Francisco
            REQ_ORG: Copyleft Certificate Co
            REQ_OU: My Organizational Unit
            REQ_CN: OpenVPN-Access
    certificate-server:
        build: 
            context: ./certificate-server
            dockerfile: ./docker/Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ./local/pki:/openvpn_pki:z
            - ./config:/config:z
